### ISSUE TITLE
Vim dependency is missed 

### ISSUE THREAD

**Issue by Gonzalo-Mier** [david-alejo/linux_install#1]
In the script to install basic things, you forgot to add the vim line.

`sudo apt install vim`

**Comment by david-alejo** [comment]
Interesting! Please correct it and put an pull request ;) Feel free to add as many packages as you wish.

**Comment by Gonzalo-Mier** [comment]
It only took me a year and a week to solve the issue :)

**Comment by david-alejo** [comment]
But you finally did it!
